spring:
  application:
  name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/databasespring?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       # dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

    open-in-view: false
logging:
  level:
    root: WARN
    #com.vicentefirtline: DEBUG

#spring.jpa.open-in-view
